### ISSUE TITLE
Add ability to close all error panels

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#118]
Let's give the user the ability to close all error panels in the site.

<img width="1108" alt="screen shot 2018-09-17 at 7 57 05 pm" src="https://user-images.githubusercontent.com/3766511/45656506-e80eda80-bab3-11e8-821e-39313eeacce7.png">

**Comment by projectyang** [comment]
Can I help with this? For clarification, the feature we want to add is a 'X' button which will allow the user to close all panels?

Also, is there a way to reproduce multiple errors in the client locally?

**Comment by helfi92** [comment]
Hey @projectyang 👋

> Can I help with this?

You can definitely help.

> For clarification, the feature we want to add is a 'X' button which will allow the user to close all panels?

Not really. What we want is to allow a user to close a error panel when an error happens. There are many places in the app where we use the `ErrorPanel` component. We'll probably need to include something like the following for most places where we use <ErrorPanel> (mainly views and some forms):

```jsx
handleErrorPanelClose = () => {
  this.setState: {
    error: null,
  };
};

// ...
<ErrorPanel onClose={this.handleErrorPanelClose} />
```

_Note: The [`ErrorPanel`](https://mozilla-frontend-infra.github.io/components/#errorpanel) component already adds a "X" button whenever the `onClose` prop is defined._

> Also, is there a way to reproduce multiple errors in the client locally?

I'm not sure you need to take this into account but you can do:

```jsx
<Fragment>
  <ErrorPanel error="First error" />
  <ErrorPanel error="Second error" />
</Fragment>
```

**Comment by helfi92** [comment]
https://github.com/taskcluster/taskcluster-web/pull/157 just got merged. You will want to pull in the latest changes before you start your work :) It's a big change.

**Comment by projectyang** [comment]
Here's my current approach, would love to hear your thoughts:

The current ErrorPanel logic is something like `{error && <ErrorPanel />}`, with error coming from the component's props. 

In order to have a handleErrorPanelClose, I'll need to add in a boolean variable to the state so it'll be something like `{error && errorClose && <ErrorPanel />}` which can be manipulated by the handler. The variable will also need to 'reset' when a new error appears.

As for adding this handler to all the views, in order to not repeat too much code, I'll wrap a higher order component e.g. withErrorHandler to all the various components using ErrorPanels.

**Comment by helfi92** [comment]
That sounds good to me. Give it a try and let's see if it works :) Feel free to implement it on one view, and then once we're sure it's the right way to go, we can integrate it in the other views.

**Comment by helfi92** [comment]
@projectyang How is it going? Is there anything I can do to help :)

**Comment by projectyang** [comment]
@helfi92 Hey, I've been out sick for the past few days. Back now and should be able to get an initial pull soon.

**Comment by helfi92** [comment]
Sorry to hear that. Sounds good. Thank you for the fantastic work you've been doing so far :)
