### ISSUE TITLE
Links in ErrorPanels are hard to read

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#127]
We should make links more readable.

![screen shot 2018-09-20 at 4 24 43 pm](https://user-images.githubusercontent.com/3766511/45844955-c56a0500-bcf1-11e8-933a-75b5b2d7de5c.png)

To reproduce the issue, go to any view and include the following in the render method:

```jsx
<ErrorPanel error="This is a [link that is hard to read]()" />
```

This should display something like:

![screen shot 2018-09-26 at 10 52 42 am](https://user-images.githubusercontent.com/3766511/46088393-54f03780-c17a-11e8-8c00-60d0193df653.png)

**Comment by preeti98** [comment]
This is my first contribution to taskcluster .So, can someone please explain the workflow to me? Thanks in advance!

**Comment by helfi92** [comment]
Hi @preeti98. The first step is to have your local development setup by going over the [README](https://github.com/taskcluster/taskcluster-web/blob/master/README.md). I believe https://github.com/taskcluster/taskcluster-web/blob/master/src/App/Main.jsx#L31-L33 is where we color links. You'll probably want to change that value to something else. Hope that helps :)

**Comment by aimenbatool** [comment]
Hi @helfi92, I have managed to setup taskcluster-web & taskcluster-web-server on the local machine. The server is working fine. 
But taskcluster-web is giving me error `Cannot read property 'includes' of undefined` in the browser. Can you please guide me further?

Also, how would I get this error? So that I can see this and play with colors? What mess would I have to make?
![taskcluster](https://user-images.githubusercontent.com/13648547/46062338-ebc0f200-c182-11e8-8289-04b914be4f32.png)

**Comment by aimenbatool** [comment]
I'm facing this **warning** also
`WARNING in EnvironmentPlugin - TASKCLUSTER_ROOT_URL environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.
`

However, I have setup TASLCLUSTER_ROOT_URL using [this](https://github.com/taskcluster/taskcluster-web-server#running-taskcluster-web-server-locally) way.

**Comment by hemakshis** [comment]
Hi @preeti98,
> WARNING in EnvironmentPlugin - LOGIN_STRATEGIES environment variable is undefined.
> 
> You can pass an object with default values to suppress this warning.
> See https://webpack.js.org/plugins/environment-plugin for example.
> ```
In order to remove this error, you will have to create a `.env` file in the root folder of the repo. Add these parameters https://github.com/taskcluster/taskcluster-web#auth0-config in it.
Also, this might be of some help -> https://github.com/taskcluster/taskcluster-web/issues/98#issuecomment-417959104

**Comment by helfi92** [comment]
For the `TASKCLUSTER_ROOT_URL environment variable is undefined` warning, you can remove this warning by modifying `user-config.yml` in taskcluster-web-server to include the rootUrl:

```json
defaults:
  taskcluster:
    rootUrl: https://taskcluster.net
```

For the LOGIN_STRATEGIES warning, you can remove it by adding `LOGIN_STRATEGIES=""` in your `.env` file of taskcluster-web.

**Comment by aimenbatool** [comment]
Thanks for the help @helfi92. 
How to reproduce this error to apply the fix? 

I appreciate your time.

**Comment by helfi92** [comment]
@aimenbatool I updated the [first comment](https://github.com/taskcluster/taskcluster-web/issues/127#issue-362351788) to help reproduce. Let me know if there's something else I can do to help :)

**Comment by preeti98** [comment]
> For the `TASKCLUSTER_ROOT_URL environment variable is undefined` warning, you can remove this warning by modifying `user-config.yml` in taskcluster-web-server to include the rootUrl:
> 
> ```json
> defaults:
>   taskcluster:
>     rootUrl: https://taskcluster.net
> ```
> 
> For the LOGIN_STRATEGIES warning, you can remove it by adding `LOGIN_STRATEGIES=""` in your `.env` file of taskcluster-web.

@helfi92 I tried to remove the LOGIN_STRATEGIES from the .env file, however, while running the application, I get the same error.

**Comment by helfi92** [comment]
@preeti98 Why are you removing `LOGIN_STRATEGIES`? It should be in `.env`.

**Comment by aimenbatool** [comment]
@helfi92 one more thing, Please. 

I followed the proecess to signin menioned in [this comment](https://github.com/taskcluster/taskcluster-web/issues/128#issuecomment-424688755).
Upon executing `$ eval $(./taskcluster signin --name taskcluster-web-server)` it doesn't show me anything in terminal but redirects me to the browser. 
See screen shot below.
![taskcluster 1](https://user-images.githubusercontent.com/13648547/46089746-9f98a080-c1c8-11e8-95ca-2162aa699e35.png)

How to fix this?
And is this required to be functional to fix this issue?

**Comment by preeti98** [comment]
Sorry, @helfi92 it was a mistake on my part.
I have successfully run taskcluster, however could you please tell me how to go to any view as mentioned in the first comment?

Here is what I see:
![upload](https://user-images.githubusercontent.com/39257049/46089878-19328d80-c1cd-11e8-988d-99377bd98f46.png)

**Comment by aimenbatool** [comment]
Thanks for help @helfi92

**Comment by preeti98** [comment]
> "This is a [link that is hard to read]()"

In many views, I see the following line already present:
```
import ErrorPanel from '@mozilla-frontend-infra/components/ErrorPanel';
```
So, do I still use the following?
```
import ErrorPanel from '../../components/ErrorPanel';
```
Also I am considering changing 
```
<ErrorPanel error={error.graphQLErrors[0].message} />
```
to
```
<ErrorPanel error="This is a [link that is hard to read]()" />
```

**Comment by helfi92** [comment]
Sorry, you are correct. It should be`import ErrorPanel from '@mozilla-frontend-infra/components/ErrorPanel';`

You can just add it on top of the already existent one. What you're doing here is simply so you can reproduce the ugly link in an error panel. Once the color is fixed, you will delete the added ErrorPanel.

**Comment by preeti98** [comment]
> Sorry, you are correct. It should be`import ErrorPanel from '@mozilla-frontend-infra/components/ErrorPanel';`
> 
> You can just add it on top of the already existent one. What you're doing here is simply so you can reproduce the ugly link in an error panel. Once the color is fixed, you will delete the added ErrorPanel.

I have modified the file: https://github.com/taskcluster/taskcluster-web/blob/master/src/views/AwsProvisioner/ViewAwsHealth/index.jsx

by adding another import statement in the beginning and by changing line no. 23 as I mentioned earlier. However I am getting the following output. Please help:
![upload1](https://user-images.githubusercontent.com/39257049/46093353-c52ba700-c1d4-11e8-8cb6-1d57f8fb9eef.png)

Please do guide me on how to proceed.

**Comment by aimenbatool** [comment]
@helfi92 making the change at [this](https://github.com/taskcluster/taskcluster-web/blob/master/src/App/Main.jsx#L31-L33) doesn't make any difference at all. 

Here is what I did just to make it working:

- Added an other constant named SECONDARY_LIGHT in [constants.js](https://github.com/taskcluster/taskcluster-web/blob/master/src/utils/constants.js#L43)

- Set [this](https://github.com/taskcluster/taskcluster-web/blob/master/src/theme.js#L38) main equals to SECONDARY_LIGHT
But this doesn't look good to me. Is there any other way? 
This fix looked easy at first but it is giving a tought time. :disappointed:

**Comment by helfi92** [comment]
@preeti98 Try testing it in `localhost:5080/provisioners`.

**Comment by aimenbatool** [comment]
Hi @helfi92, I think I have found the solution. Please, see my process and verify if this is the right way to do?

No style is being applied to ErrorPanel while making changes at [this line](https://github.com/taskcluster/taskcluster-web/blob/master/src/App/Main.jsx#L31-L33)

After a lot of digging to our code and the codebase of our third-party component `ErrorLayout`, I came to the conclusion that the proper place to make this change is in [`ErrorLayout` component](https://github.com/aimenbatool/components).
And, Here is what I have done:

- I explored ErrorPanel in [component repo](https://github.com/aimenbatool/components) 

- I figured out that no color for anchor tag is defined in [ErrorPanel](https://github.com/aimenbatool/components/blob/master/src/components/ErrorPanel/index.jsx#L47-L49) 

- I set anchor color for error text and it is working like a charm
Now, wherever this ErrorPanel will be included it will make anchor white on a red background

See a screenshot below.
![mozilla frontend infra components style guide](https://user-images.githubusercontent.com/13648547/46167531-71da5700-c2af-11e8-95ea-10422864bf93.png)

Mentioning again, the app is not picking any changes from [these lines](https://github.com/aimenbatool/components/blob/master/src/components/ErrorPanel/index.jsx#L47-L49). I have spent hours but nothing works except making the direct change in the constant file which is not a good approach. 

Since, css-in-js (i.e. JSS) adds unique identifier to the class names, so you cannot css to third party components.
> JSS generates unique class names by default when it compiles JSON representation to CSS.

Should I make a PR to Component repo and apply these changes? 

Please, share your thoughts on it.
Thanks!

**Comment by aimenbatool** [comment]
Sounds good. I'm going to start working on this pull request now.

**Comment by helfi92** [comment]
https://github.com/mozilla-frontend-infra/components/pull/24#issuecomment-426376909

@aimenbatool Do you want to update the repo to use the updated version?

**Comment by aimenbatool** [comment]
@helfi92 Yes sure.
Opening a PR right now.
