### ISSUE TITLE
error regarding task that does not exist, when it does..

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#219]
Seen at https://taskcluster-web.netlify.com/tasks/5ez-I6XXQzuBSDi6FFlvoQ

(note, too, the contrast in the error message)

**Comment by helfi92** [comment]
@djmitche Is it possible the task had no run available? If that's the case then it has been fixed in https://github.com/taskcluster/taskcluster-web/pull/240. Any task without a run was previously throwing an error. Let me know if you can replicate the issue. The task in the issue description seem to have expired.

**Comment by djmitche** [comment]
Hm, possible.  I'll re-open if I can repro.
