### ISSUE TITLE
Reduce page size in scopes view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#267]
STR:

1. Navigate to http://localhost:5080/auth/scopes
2. Click on the "Clients" tab

Actual: The list shows a lot of clients (>20).
Expected: The paginated list shows at most 10 clients at a time so that users don't have to scroll down to click "Next page".

**Comment by alecclarke** [comment]
@helfi92 could I grab this one?

**Comment by helfi92** [comment]
Go for it.

**Comment by alecclarke** [comment]
@helfi92 Is there an easy way to generate 10+ clients to be displayed?

I could be missing something obvious here but I'm getting the following error when accessing  http://localhost:5080/auth/scopes :

![screen shot 2018-11-10 at 6 28 06 am](https://user-images.githubusercontent.com/8182434/48302446-e826c780-e4b1-11e8-81b3-9cfedf12e1f7.png)

**Comment by helfi92** [comment]
I wonder if taskcluster-web-server is configured properly on your machine. Try doing what’s in https://github.com/taskcluster/taskcluster-web/issues/163#issuecomment-429662157 and see if that fixes it.

**Comment by alecclarke** [comment]
That did the trick! Thanks!

**Comment by alecclarke** [comment]
@helfi92 I believe the root of this issue is from the call to [extractExpandedScopes(clientsConnection.edges)](https://github.com/taskcluster/taskcluster-web/blob/master/src/components/ClientScopesTable/index.jsx#L90). While the number of edges (clients) is indeed 10 - the aggregated expanded scopes for each of the clients has no limit (in this case ~120).

Is the intended behaviour to paginate the expandedScopes by page sizes of 10?

**Comment by helfi92** [comment]
Ah, good catch!! I'm afraid we might introduce too many complications if we paginate expandedScopes. I guess we can keep it the way it is. Many thanks for looking into it.
