### ISSUE TITLE
Clients view: one scope per line

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#354]
Navigate to https://taskcluster-web.netlify.com/auth/clients/email%2Fbastien%40nextcairn.com%2Ftc-notify-test. The scopes text area expects one scope per line.

![screen shot 2019-01-04 at 9 38 54 am](https://user-images.githubusercontent.com/3766511/50693313-9491af80-1004-11e9-8b54-5b4e225d290b.png)

Problem: Some users don't know that scopes are separated by new lines so they end up separating them via a comma or a space.

Solution: Add a helper text to the scopes text area via the [`helperText`](https://material-ui.com/api/text-field/#props) prop with text `1 scope per line`.

**Comment by vivekRaj10** [comment]
Hi @helfi92, I am new to open source. I would like to work on this issue. Please let me know how can I start with it?

**Comment by vivekRaj10** [comment]
Hi @helfi92 , I have cloned taskcluster-web-server repo & installed the dependencies using yarn. I am not able to configure `taskcluster.rootUrl` because my user-config-template.yml is empty & there is no user-config.yml file in the folder structure. Please take a look at the attached screenshots
![screenshot 2019-01-14 at 4 19 23 am](https://user-images.githubusercontent.com/9269822/51091712-43c44880-17b4-11e9-84ea-d28000a2236d.png)
![screenshot 2019-01-14 at 4 23 26 am](https://user-images.githubusercontent.com/9269822/51091713-43c44880-17b4-11e9-8e7b-a457056bfaf7.png)

**Comment by helfi92** [comment]
> I am not able to configure taskcluster.rootUrl because my user-config-template.yml is empty & there is no user-config.yml file in the folder structure.

1. Create a new file `user-config.yml`at the root directory
2. Copy the content of user-config-template.yml into user-config.yml
3. Edit user-config.yml to have the rootUrl set to `https://taskcluster.net` instead of ...

https://github.com/taskcluster/taskcluster-web-server#running-taskcluster-web-server-locally

Once this is done, you would be able to run the server via `yarn install` to instal the dependencies and `yarn start` to start the server. Hope that helps.

**Comment by vivekRaj10** [comment]
Hi @helfi92 , My local environment is up and running. I have added the `helperText` as mentioned and it looks fine on my local. So, what's next I have to do ?

**Comment by helfi92** [comment]
The next step is to create a pull-request.
